# Generated by Django 5.2.6 on 2025-09-13 16:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Price cannot be negative.')])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Stock cannot be negative.')])),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
